In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=pd.read_csv("weatherAUS[1].csv")
df.head(3)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   

   RainTomorrow  
0            No  
1            No  
2            No  

[3 rows x 23 columns]

In [ ]:
x=df.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]]
y=df.iloc[:,-1].values

In [ ]:
x.head()

Location  MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0   Albury     13.4     22.9       0.6           W           44.0          W   
1   Albury      7.4     25.1       0.0         WNW           44.0        NNW   
2   Albury     12.9     25.7       0.0         WSW           46.0          W   
3   Albury      9.2     28.0       0.0          NE           24.0         SE   
4   Albury     17.5     32.3       1.0           W           41.0        ENE   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm RainToday  
0       1007.7       1007.1       8.0       NaN     16.9     21.8        No  
1       1010.6       1007.8       NaN       NaN     17.2     24.3        No  
2       1007.6       1008.7       NaN       2.0     21.0     23.2        No  
3       1017.6       1012.8       NaN       NaN     18.1     26.5        No  
4       1010.8       1006.0       7.0       8.0     17.8     29.7        No

In [ ]:
y=y.reshape(-1,1)

In [ ]:
y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [ ]:
x.isnull().sum()

Location             0
MinTemp           1196
MaxTemp           1012
Rainfall          2342
WindGustDir       6281
WindGustSpeed     6273
WindDir9am        7785
WindDir3pm        2970
WindSpeed9am      1448
WindSpeed3pm      2067
Humidity9am       2066
Humidity3pm       2487
Pressure9am      10656
Pressure3pm      10609
Cloud9am         33478
Cloud3pm         34502
Temp9am           1563
Temp3pm           2040
RainToday         2342
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
impu=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [ ]:
x=impu.fit_transform(x)
y=impu.fit_transform(y)

In [ ]:
y


array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [ ]:
 from sklearn.preprocessing  import LabelEncoder
 le = LabelEncoder()
 x[:,0]=le.fit_transform(x[:,0])

In [ ]:
le = LabelEncoder()
x[:,4]=le.fit_transform(x[:,4])
le = LabelEncoder()
x[:,6]=le.fit_transform(x[:,6])

In [ ]:
le = LabelEncoder()
x[:,7]=le.fit_transform(x[:,7])
le1 = LabelEncoder()
y=le1.fit_transform(y)

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
le = LabelEncoder()
x[:,-1]=le.fit_transform(x[:,-1])

In [ ]:
x

array([[-1.65691649,  0.35432813,  0.11094356, ...,  0.1889065 ,
         0.17416037,  0.        ],
       [-1.65691649, -0.63277254,  0.43204888, ...,  0.23898104,
         0.55149426,  0.        ],
       [-1.65691649,  0.27206974,  0.51962305, ...,  0.87325853,
         0.38546735,  0.        ],
       ...,
       [-1.18255313,  0.0746496 , -0.19556607, ...,  0.28905558,
        -0.2786403 ,  0.        ],
       [-1.18255313,  0.05819793, -0.18097037, ...,  0.15552347,
        -0.03714661,  0.        ],
       [-1.18255313, -0.05696382,  0.03796507, ..., -0.07815771,
         0.20434708,  0.        ]])

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler() 
x=sc.fit_transform(x)

In [ ]:
x

array([[-1.65691649,  0.35432813,  0.11094356, ...,  0.1889065 ,
         0.17416037, -0.53468267],
       [-1.65691649, -0.63277254,  0.43204888, ...,  0.23898104,
         0.55149426, -0.53468267],
       [-1.65691649,  0.27206974,  0.51962305, ...,  0.87325853,
         0.38546735, -0.53468267],
       ...,
       [-1.18255313,  0.0746496 , -0.19556607, ...,  0.28905558,
        -0.2786403 , -0.53468267],
       [-1.18255313,  0.05819793, -0.18097037, ...,  0.15552347,
        -0.03714661, -0.53468267],
       [-1.18255313, -0.05696382,  0.03796507, ..., -0.07815771,
         0.20434708, -0.53468267]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(y_train)

[0 0 0 ... 0 1 1]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
clas=RandomForestClassifier(n_estimators=100,random_state=0)
clas.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
clas.score(x_train,y_train)

0.9998848937425361

In [ ]:
y_pre=clas.predict(x_test)

In [ ]:
y_pre=le1.inverse_transform(y_pre)
y_test=le1.inverse_transform(y_test)

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:154: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pre

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
y_pre=y_pre.reshape(-1,1)
y_test=y_test.reshape(-1,1)

In [ ]:
dfy=np.concatenate((y_test,y_pre),axis=1)

In [ ]:
dfy=pd.DataFrame(dfy,columns=['Rain tommorrow','rain pediction'])

In [ ]:
dfy

Rain tommorrow rain pediction
0                 No             No
1                 No             No
2                 No             No
3                Yes            Yes
4                Yes             No
...              ...            ...
17371            Yes             No
17372             No             No
17373             No             No
17374             No             No
17375             No             No

[17376 rows x 2 columns]

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pre)

0.852152394106814